### ISSUE TITLE
Can not use websocket protocol in mqtt version 1.1.0 in android

### ISSUE THREAD

**Issue by kazixma** [eclipse/paho.mqtt.android#103]
I use dependencies from repositories "https://repo.eclipse.org/content/repositories/paho-releases/"
   compile 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.0'
    compile 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.0@aar'

And I connect to "ws://url:port" and can not connect to server . 

Thankyou

**Comment by jpwsutton** [comment]
We'll need more information before we can look at this. If you have any logs, stack traces or code snippets to show exactly what's happening please add them to the issue.

**Comment by kazixma** [comment]
Sorry, it is my mistake , I can connect by websocket but keepalive can not use , For example I set keepalive 30 second , when 30 second ago , it show me " connection lost".
Thank @jpwsutton

**Comment by jpwsutton** [comment]
Looks like this is a dup of Issue #104, closing as such.
