### ISSUE TITLE
GCM messages not getting delivered once MQTT is connected

### ISSUE THREAD

**Issue by pavan2you** [eclipse/paho.mqtt.android#106]
Please fill out the form below before submitting, thank you!

- [YES ] Bug exists Release Version 1.1.0 (Java Repository Master Branch)
- [ YES] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Android Service Repository Master Branch)

__Android API Version Bug Seen on:__
API Level above 15

__Android Version Bug Seen on:__
4.1 onwards

Please also check that if you have found the bug in the Release version (1.1.0) that you check that it also exists in the Snapshot (1.1.1-SNAPSHOT) before raising a bug.

## Description of Bug:
E.g. Steps to re-create, how often does this happen etc..

1. in sample app, Please register for GCM
2. Establish connection to MQTT server/broker
3. Try to send push notification from GCM. (observe {"error":"NotRegistered"} from Google in your_test_server).

**Comment by jpwsutton** [comment]
Strange, GCM (Google Cloud Messaging) & MQTT are very different protocols (GCM uses XMPP or HTTP). In your steps to recreate, can you receive messages from GCM up until the point where you connect to the MQTT broker?

Do you see any error messages in the Android app itself?

**Comment by pavan2you** [comment]
Hi this is my mistake, sorry for inconvenience.
