### ISSUE TITLE
Application Not Responding when I open application and not use.

### ISSUE THREAD

**Issue by kazixma** [eclipse/paho.mqtt.android#107]
Please fill out the form below before submitting, thank you!
- [ x] Bug exists Release Version 1.1.0 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__23

__Android Version Bug Seen on:__Mashmallow

Please also check that if you have found the bug in the Release version (1.1.0) that you check that it also exists in the Snapshot (1.1.1-SNAPSHOT) before raising a bug.
## Description of Bug:

E.g. Steps to re-create, how often does this happen etc..

I open application , and Mqtt connect all time ( I use reconnect and setkeeplive) , then I don't use application but I open application . And Application is show "Application not responding"
Thankyou Sir

**Comment by jpwsutton** [comment]
This could just be your application not responding or a problem with the service. Could you get any logs that show what's happening under the covers leading up until the app becomes unresponsive, I would expect to see some exceptions being thrown though.

**Comment by jpwsutton** [comment]
Is there any followup on this Issue or can I close it? Thanks.
