### ISSUE TITLE
Connection lost when new deivce subscribe same topic

### ISSUE THREAD

**Issue by dev-chulbuji** [eclipse/paho.mqtt.android#109]
Please fill out the form below before submitting, thank you!

- [x] Bug exists Release Version 1.1.0 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Android Service Repository Master Branch)
- [x] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__

__Android Version Bug Seen on:__

Please also check that if you have found the bug in the Release version (1.1.0) that you check that it also exists in the Snapshot (1.1.1-SNAPSHOT) before raising a bug.

## Description of Bug:
Hi i am trying to make android application for smart switch using mqtt eclipse library.
if any device subscribed certain topic (E.G. "test"), device has lost connection when other device subscribe same topic ("test"). is this bug in library or not?
and i trying to test for org.eclipse.paho.android.sample. but i cannot run this project because 
"error: package org.eclipse.paho.client.mqttv3 does not exist"
 
## Console Log output (if available):
![image](https://cloud.githubusercontent.com/assets/20170132/17286313/ae454056-5803-11e6-8de4-493554edee4e.png)

![image](https://cloud.githubusercontent.com/assets/20170132/17286327/ca76e9d2-5803-11e6-8825-d5a5938e37ad.png)

**Comment by jpwsutton** [comment]
Hi,

Are you using the same client ID for both devices? If this is the case then once the second device connects, the first one will be disconnected by the broker as it will think that they are the same device and that the first connection has gone stale.

The problem about missing mqttv3 is a common one for that repository as it's the core project that the service is built from and so has some temperamental settings that don't always work for users.

Try using this standalone example: https://github.com/jpwsutton/paho-android-standalone

**Comment by dev-chulbuji** [comment]
Oh.. i am using same client ID. Thx for ur help!
