### ISSUE TITLE
AlarmPingSender not work correctly on Motorola phone

### ISSUE THREAD

**Issue by pengan1987** [eclipse/paho.mqtt.android#122]
Please fill out the form below before submitting, thank you!

- [x] Bug exists Release Version 1.1.0 (Java Repository Master Branch)
- [x] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__
23
__Android Version Bug Seen on:__
Android 5.1.1 (Moto X 2013)

Please also check that if you have found the bug in the Release version (1.1.0) that you check that it also exists in the Snapshot (1.1.1-SNAPSHOT) before raising a bug.

## Description of Bug:
This code will not work on Motorola device, because getIntExtra always returns default value -1 and won't throw ClassCastException, so the catch code will never reached. 
```java
//AlarmPingSender.java
//org.eclipse.paho.android.service.AlarmPingSender, starts from line 132
try {
	count = intent.getIntExtra(Intent.EXTRA_ALARM_COUNT, -1);
} catch (ClassCastException ex){
	// This is a Motorola Phone (Probably a Moto G or X)
	// And so Intent.EXTRA_ALARM_COUNT is actually a Long!
	Long longCount = intent.getLongExtra(Intent.EXTRA_ALARM_COUNT, -1);
	count = longCount.intValue();
}
```
A possible fix code will look like this
```java
try {
    count = intent.getIntExtra(Intent.EXTRA_ALARM_COUNT, -1);
    if (count == -1) {
        // getIntExtra fails, may be a Motorola phone, try with getLongExtra
        Long longCount = intent.getLongExtra(Intent.EXTRA_ALARM_COUNT, -1);
        count = longCount.intValue();
    }
} catch (ClassCastException ex) {
    // I'm not sure this code is version safe
    // Keep this try catch structure to prevent crash
    count = -1;
}
```

**Comment by jpwsutton** [comment]
Turns out that the code itself is just used for a fairly useless log statement, so I'm just opting to remove it entirely, thanks for your suggestion though!
