### ISSUE TITLE
Fatal crash when attempting to connect when server is not running 

### ISSUE THREAD

**Issue by spectrl** [eclipse/paho.mqtt.android#123]
Please fill out the form below before submitting, thank you!
- [x] Bug exists Release Version 1.1.0 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

**Android API Version Bug Seen on:**

**Android Version Bug Seen on:**

Please also check that if you have found the bug in the Release version (1.1.0) that you check that it also exists in the Snapshot (1.1.1-SNAPSHOT) before raising a bug.
## Description of Bug:

If I try to call `connect()` on the `MqttAndroidClient` while the server is not running, it causes the app to crash before the exception can be caught.
`onFailure` is called in the `IMqttActionListener` that is passed to the `connect()` call, but the `Throwable`argument received there is null, and the catch block surrounding the `connect()`method call is never even reached before the app crashes.
## Console Log output (if available):

`java.lang.NullPointerException: cancel() called with a null PendingIntent
                                                                                   at android.app.AlarmManager.cancel(AlarmManager.java:890)
                                                                                   at org.eclipse.paho.android.service.AlarmPingSender.stop(AlarmPingSender.java:87)
                                                                                   at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:353)
                                                                                   at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:668)
                                                                                   at java.lang.Thread.run(Thread.java:761)`

**Comment by jpwsutton** [comment]
Hi, I've been unable to replicate this in the SNAPSHOT version, could you verify that you get the same behaviour using that please?

**Comment by muthuprabhu-kp** [comment]
I am facing same issue in Android N. and i am using Snapshot Version 1.1.1-SNAPSHOT

**Comment by jpwsutton** [comment]
Interesting, I've attempted to recreate this using the example app, by pointing it at a closed port on a server (Which should re-create the effect of not having the server running) and still cannot get this to happen. Is there anything you are doing differently in your application to what the example app is doing when connecting?

**Comment by Zugreiter** [comment]
Hey,

i have the exactly same issue as described here. i'm able to recreate the issue by using different internet protocol versions. if i use my routers wifi with an **ipv6 address** i get the this error. if i turn off wifi and use mobile internet of the phone (which connects through ipv4) everything went fine.

maybe this helps

**Comment by spectrl** [comment]
For me, this disappeared as soon as I switched to the SNAPSHOT version.

**Comment by pavan2you** [comment]
Hi
Steps to reproduce this are very easy.

1) Make sure you connected to Some Mqtt Broker
2) Put device on airplane mode
3) If you relaunch application app will crash (Here key point is connection establishing logic will get trigger.. but as device is in AirplaneMode app will crash).

**Comment by pavan2you** [comment]
There is a simple workaround to fix this issue.

Make sure you will be connecting to broker only after knowing network(internet) is available. I've tested and the issue is fixed.

**Comment by existenz31** [comment]
I confirm the issue on version 1.1.0 and Android 24 (M).
I have upgraded to SNAPSHOT 1.1.1 for both client.mqttv3 and android.service => problem fixed
Thx @spectrl
