### ISSUE TITLE
repo.eclipse.org is down, again :(

### ISSUE THREAD

**Issue by noordawod** [eclipse/paho.mqtt.android#125]
Compilation is now stuck because the server is down. This tends to happen every few weeks, for the last few months. Maybe find a solution?

Anyway, please reboot it...

Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.0 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__

__Android Version Bug Seen on:__

Please also check that if you have found the bug in the Release version (1.1.0) that you check that it also exists in the Snapshot (1.1.1-SNAPSHOT) before raising a bug.

## Description of Bug:
E.g. Steps to re-create, how often does this happen etc..

**Comment by jpwsutton** [comment]
A bug against eclipse has already been raised here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=502356, the repository should be back online as soon as possible.

**Comment by jpwsutton** [comment]
It's back up.

**Comment by noordawod** [comment]
... and it's down again.

**Comment by jpwsutton** [comment]
I've re-opened the bug. 
Might I suggest raising the bug yourself at bugs.eclipse.org in the future? 
If you just raise it against us every time, you will have to wait for myself or another committer to notice it, then go to bugs.eclipse.org to raise it over there which will take longer.

I believe that there is also a bug raised to increase the SLA level of repo.eclipse.org to tier 2 which if accepted, should mean that it is recovered a lot faster than present.

**Comment by jpwsutton** [comment]
And back up.

**Comment by noordawod** [comment]
I figured it out before you suggested it and opened myself an Eclipse account few hours ago. Sadly, however, it takes few hours/days to be accepted so next time I'll open the bug report there.

Thanks for your help @jpwsutton so far.

**Comment by noordawod** [comment]
Well, 2 weeks passed and my account hasn't been approved to use Eclipse.org. One would think it's the Pentagon's website for such a prolonged approval time...

I got no way to notify them about the situation: **server is down again...**

**Comment by akalankapagoda** [comment]
Down again for the second time this week.

**Comment by jpwsutton** [comment]
@akalankapagoda Issue has been reopened here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=508658
