### ISSUE TITLE
com.github.sschuberth:sdk-manager-plugin:master-SNAPSHOT is not avaible

### ISSUE THREAD

**Issue by zhangjinself** [eclipse/paho.mqtt.android#138]
Error:A problem occurred configuring root project 'code'.

> Could not resolve all dependencies for configuration ':classpath'.
> Could not resolve com.github.sschuberth:sdk-manager-plugin:master-SNAPSHOT.
>      Required by:
>          :code:unspecified
>       > Could not resolve com.github.sschuberth:sdk-manager-plugin:master-

SNAPSHOT.
         > Unable to load Maven meta-data from 

https://jitpack.io/com/github/sschuberth/sdk-manager-plugin/master-

SNAPSHOT/maven-metadata.xml.
            > Could not GET 'https://jitpack.io/com/github/sschuberth/sdk-

manager-plugin/master-SNAPSHOT/maven-metadata.xml'. Received status code 401 from 

server: Repo not found or no access token provided

this project don't find. so your project need update

**Comment by jpwsutton** [comment]
This was resolved in the develop branch a few days ago: https://github.com/eclipse/paho.mqtt.android/tree/develop

**Comment by luckcoolla** [comment]
+1, there is an issue in the master branch. Switching to dev

**Comment by zhangjinself** [comment]
thanks

**Comment by jpwsutton** [comment]
The master branch has been updated to remove this plugin so should work fine now.
