### ISSUE TITLE
How to cancel auto reconnect mechanism when internet is not available?

### ISSUE THREAD

**Issue by hahasheminejad** [eclipse/paho.mqtt.android#141]
We are using MqttAndroidClient and it works just fine. However we want to cancel auto reconnect mechanism after for example 10 failure tries when network connectivity is not available. 

In this case, we want to close or disconnect the current MqttAndroidClient session and later when user have access to the internet, we connect it again (we don't want to leave Mqtt service running, reconnecting and draining battery). 

Now by invoking disconnect method on an instance of MqttAndroidClient which is still alive and trying to reconnect, nothing will happen (still trying to reconnect). In addition, if the next time when user have access to the internet, we create a new object and connect it to the server, the previous instance also can connect and it causes a duplicate connection issue on the server while two simultaneous client are connecting with a common clientId.

Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.0 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__

__Android Version Bug Seen on:__

Please also check that if you have found the bug in the Release version (1.1.0) that you check that it also exists in the Snapshot (1.1.1-SNAPSHOT) before raising a bug.

## Description of Bug:
E.g. Steps to re-create, how often does this happen etc..

**Comment by hamidrezabstn** [comment]
my suggestion is not using paho default service and create your own background service for connections. that would help you a lot because you have lots of flexibility . for example start connection on network connected and limit your retry attemps , ...

**Comment by hahasheminejad** [comment]
@hamidrezabstn Thank you for your swift reply. Right now we have a service for our app individually and inside onCreate we make a MQTT connection to the server. But still we don't know or are unable to stop this reconnecting instance! Can u plz provide us an example?

**Comment by hamidrezabstn** [comment]
@hahasheminejad 
hi ! 
just for the record , which MQTT broker you use ? we use mosquitto btw!

right now i guess you use paho service in your app which is responsible for client connection! 

drop using that by removing it from your manifest file and create your own service by extending Service class of android api and handle connection states using your service ! 

another thing that came in my mind is to use paho android example which use their default service and see how they handle different state of the connection!

**Comment by miketran78727** [comment]
Back to the original question "How to cancel auto reconnect"  You should be able to call connect() again with new options to cancel automatic reconnect.  If that does not work, then it is a bug because it was the design https://github.com/eclipse/paho.mqtt.java/issues/9

**Comment by hahasheminejad** [comment]
Thank you all for your answers especially @hamidrezabstn . I will keep here updated once we implement one of your suggested methods.
