### ISSUE TITLE
Snapshot version 1.1.1-20161102.042337-71 is not uploaded in repository

### ISSUE THREAD

**Issue by baole** [eclipse/paho.mqtt.android#148]
Please check it in this folder

https://repo.eclipse.org/content/repositories/paho-snapshots/org/eclipse/paho/org.eclipse.paho.client.mqttv3/1.1.1-SNAPSHOT/

**Comment by baole** [comment]
Gradle build system is failed to download this snapshot dependency.

**Comment by jpwsutton** [comment]
This was an issue caused by my attempts to get javadoc jars into the maven repo. I've undone the changes and have spun a new nightly build so the problem should be resolved.
