### ISSUE TITLE
Can I use single service for multiple application?

### ISSUE THREAD

**Issue by yuebinyun** [eclipse/paho.mqtt.android#149]
First of all,  thank you for your code.
I just hope I can use **single service for multiple application**, I think it more battery-effective.

**Comment by jpwsutton** [comment]
I think you would have to compile the service into it's own APK, however I'm not 100% sure about this: http://stackoverflow.com/questions/34483823/how-to-run-a-singleton-shared-service-in-a-library-for-multiple-applications

**Comment by jpwsutton** [comment]
@yuebinyun Did this solve your problem?

**Comment by yuebinyun** [comment]
@jpwsutton -- Sorry for my late reply.  I'm not sure when to  use android AIDL.
