### ISSUE TITLE
Key android.intent.extra.ALARM_COUNT expected Integer but value was a java.lang.Long

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.android#15]
migrated from Bugzilla [#467954](https://bugs.eclipse.org/bugs/show_bug.cgi?id=467954)
status UNCONFIRMED severity _normal_ in component _MQTT-Android_ for _1.2_
Reported in version _unspecified_ on platform _Other_
Assigned to: James Sutton

Original attachment names and IDs:
- _[paho-android-service-st.txt](https://bugs.eclipse.org/bugs//attachment.cgi?id=253655)_ (ID 253655)

On 2015-05-22 01:51:10 -0400, Guillermo Casanova wrote:

> Created attachment 253655
> Bug stacktrace
> 
> Paho android service AlarmPingSender class method on onReceive of the AlarmReceiver gets served a Long object but it expects an Integer. Check out the attached stacktrace.

On 2015-08-17 06:29:27 -0400, Ian Craggs wrote:

> Assigning to James

On 2015-09-02 05:43:01 -0400, James Sutton wrote:

> That's very strange.. I've had a dig through and everything I can find points to that value being an Integer, it's managed by the Android Alarm manager so I don't think it can be anything that the Android Mqtt Service is doing..
> 
> The only thing I could find that seems to match this is an issue on another Android OS project: https://github.com/mendhak/gpslogger/issues/337
> 
> You're not using a Moto G by any chance are you?
> 
> They have a fix which looks like it will work,  but it's likely that we would have to rely on you to make sure that it is fixed.(https://github.com/mendhak/gpslogger/commit/SHA: 9ae9f295d218b5b89dce3e554e04207c1fc673d7)

On 2015-09-02 06:23:23 -0400, Guillermo Casanova wrote:

> Hi James,
> 
>  I mostly use a Moto G, that's correct. I will take a look at the fix you linked, thanks a lot.

On 2015-11-18 04:30:57 -0500, James Sutton wrote:

> Hi Guillermo, 
> 
> Did this work for you? If so it might be good to add it to the Android service properly so that Paho isn't broken on the Moto G.

**Comment by Sushinn** [comment]
I have the same problem when using my application on a Moto X 2014. However when I run it on a Galaxy S5, it does not throw this exception.

Any news on this?

**Comment by jpwsutton** [comment]
The fix is pretty simple, I didn't get conformation that this worked so had left it be (as it was impossible for me to test without a Moto G). 

As this is affecting more models of phones I'll pop the change into Develop today and you'll be able to test it out in the 1.0.3-SNAPSHOT build tomorrow.

Wondering what on earth makes certain Motorola phones behave this way....

**Comment by jpwsutton** [comment]
@marciogranzotto  Has this resolved the issue for you, can I close it?

**Comment by marciogranzotto** [comment]
@jpwsutton sorry for the late reply. It it resolved the issue! Thanks!
