### ISSUE TITLE
Offline buffering does not work if network is off on app start

### ISSUE THREAD

**Issue by satyadeepk** [eclipse/paho.mqtt.android#150]
- [x] Bug exists Release Version 1.1.0 (Java Repository Master Branch)
- [x] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__
23
__Android Version Bug Seen on:__
6.0.0

## Description of Bug:
I used the paho.mqtt.java.example app. I need the offline buffering to work even if the network is unavailable on app start.
So, I have just updated the `PahoExampleActivity` to set buffer options in `onFailure` as well.
```
mqttAndroidClient.connect(mqttConnectOptions, null, new IMqttActionListener() {
                @Override
                public void onSuccess(IMqttToken asyncActionToken) {
                    DisconnectedBufferOptions disconnectedBufferOptions = new DisconnectedBufferOptions();
                    disconnectedBufferOptions.setBufferEnabled(true);
                    disconnectedBufferOptions.setBufferSize(100);
                    disconnectedBufferOptions.setPersistBuffer(true);
                    disconnectedBufferOptions.setDeleteOldestMessages(false);
                    mqttAndroidClient.setBufferOpts(disconnectedBufferOptions);

                    subscribeToTopic();
                }

                @Override
                public void onFailure(IMqttToken asyncActionToken, Throwable exception) {
                    DisconnectedBufferOptions disconnectedBufferOptions = new DisconnectedBufferOptions();
                    disconnectedBufferOptions.setBufferEnabled(true);
                    disconnectedBufferOptions.setBufferSize(100);
                    disconnectedBufferOptions.setPersistBuffer(true);
                    disconnectedBufferOptions.setDeleteOldestMessages(false);
                    mqttAndroidClient.setBufferOpts(disconnectedBufferOptions);

                    addToHistory("Failed to connect to: " + serverUri);
                }
            });
```
Upon debugging I noticed that in `ClientComms#sendNoWait`, `isResting()` is coming as false. Hence `persistBufferedMessage` is not being called.

Is it because the default value of `resting` flag is `false`? Since the connection did not succeed yet, the default value might be coming.

**Comment by miketran78727** [comment]
This currently works as design. The application must successfully connected once before automatic reconnect and offline buffering become effective.  There is already a feature request to change this behavior, see https://github.com/eclipse/paho.mqtt.java/issues/233

**Comment by satyadeepk** [comment]
@miketran78727 That's strange considering that android apps can be killed by the user and fresh connects are quite common with WiFi off.

This effectively means that I will have to queue messages into my own buffer before publishing them to Paho. Do you see any workaround for using the DisconnectedBuffer itself for this? (even if it involves forking the java/android clients)

**Comment by jpwsutton** [comment]
If you wanted to, you'd need to fork the Java client and modify sendNoWait in ClientComms (https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.client.mqttv3/src/main/java-templates/org/eclipse/paho/client/mqttv3/internal/ClientComms.java#L145).
