### ISSUE TITLE
Should be able to publishing when client is disconnected

### ISSUE THREAD

**Issue by paulo-raca** [eclipse/paho.mqtt.android#156]
Hello, and thanks for the awesome library.
I've just started using it, and it makes Android development really easy!

I've no idea whenever this is a bug, feature request, or if I'm just doing it wrong, please advise:

I want to publish a message using MqttAndroidClient so that.
- If the client is connected, great, it is sent through immediately.
- If it is not, I want it to be stored and automatically sent when a connection is stabilished
(if QoS > 0)

As far as I could tell, to do that I just had to set an `MqttClientPersistence` when creating a client, but I had no success on that -- The IMqttActionListener says it has failed, and it is never retried afterwards.

--- 

Please fill out the form below before submitting, thank you!

- [x] Bug exists Release Version 1.1.0 (Java Repository Master Branch)
- [X] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on: 25

__Android Version Bug Seen on: 7.1.1

**Comment by jpwsutton** [comment]
Hi, This is currently designed behaviour (See: https://github.com/eclipse/paho.mqtt.android/issues/150)

However as there have been a few people asking for the ability to publish before connect, We've got an enhancement on the backlog to change this in the future: https://github.com/eclipse/paho.mqtt.java/issues/233
