### ISSUE TITLE
Task exportJar not found

### ISSUE THREAD

**Issue by NguyenDucTuong** [eclipse/paho.mqtt.android#165]
I tried to build by using "gradlew.bat clean assemble exportJar". However, I failed, and the error message is "Task 'exportJar' not found in root project 'paho.mqtt.android-master'. So could you tell me where can I found the task 'exportJar'?

**Comment by NguyenDucTuong** [comment]
I tried to build from source. However, I failed, and the error is: Task 'exportJar' not found in root project 'paho.mqtt.android-master'. So how can I find task 'exportJar'

**Comment by jpwsutton** [comment]
Thanks for spotting this, we've changed our build process slightly so we need to change our docs.
The new command that should work would be something like:

`gradlew.bat clean org.eclipse.paho.android.service:assemble org.eclipse.paho.android.service:publish`

Could you try that and let us know if that works for you?

**Comment by plzgetaway** [comment]
51 errors
20 warnings
:org.eclipse.paho.android.service:generatereleaseJavadoc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':org.eclipse.paho.android.service:generatereleaseJavadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): 'D:\Down\paho.mqtt.android\org.eclipse.paho.android.service\build\tmp\generatereleaseJavadoc\javadoc.options'

**Comment by jpwsutton** [comment]
@plzgetaway Does your comment have any connection to this issue? What command did you run to initiate the build? Which branch are you pulling?

**Comment by plzgetaway** [comment]
@jpwsutton downloaded Branch:develop source. and used "gradlew.bat clean org.eclipse.paho.android.service:assemble org.eclipse.paho.android.service:publish" with your comment directly.

**Comment by jpwsutton** [comment]
Looks like it's not an error, I replicated the same process and got the `BUILD SUCCESSFUL` message at the end. The above errors were also there, but they are not an issue: https://discuss.gradle.org/t/could-not-find-metadata-maven-metadata-xml-in-remote/11720/2

**Comment by Devofure** [comment]
Documentation should be updated to the latest build setup. Still the same old documentation since before 2016
