### ISSUE TITLE
MqttAndroidClient.close() crashed due to NullPointerException

### ISSUE THREAD

**Issue by alanywlee** [eclipse/paho.mqtt.android#169]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.0 (Java Repository Master Branch)
- [v] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__

__Android Version Bug Seen on:__

Please also check that if you have found the bug in the Release version (1.1.0) that you check that it also exists in the Snapshot (1.1.1-SNAPSHOT) before raising a bug.

## Description of Bug:
E.g. Steps to re-create, how often does this happen etc..

MqttAndroidClient.close() not check if  this.mqttService is null, I accidentally crashed  in the line 
           this.clientHandle = this.mqttService.getClient(this.serverURI, this.clientId, this.myContext.getApplicationInfo().packageName, this.persistence);

due to NullPointerException

-----
    public void close() {
        if(this.clientHandle == null) {
            System.out.println(this.serverURI);
            System.out.println(this.clientId);
            System.out.println(this.myContext.getApplicationInfo().packageName);
            System.out.println(this.persistence);
            this.clientHandle = this.mqttService.getClient(this.serverURI, this.clientId, this.myContext.getApplicationInfo().packageName, this.persistence);
        }

        this.mqttService.close(this.clientHandle);
    }
----

**Comment by jpwsutton** [comment]
Thanks for finding this, I've committed a change that checks whether mqttService is null before attempting to close it.
