### ISSUE TITLE
Connect lib files directly

### ISSUE THREAD

**Issue by Serob** [eclipse/paho.mqtt.android#179]
Is there a way to connect libraries without maven or gradle but directly, like adding files into _'lib'_ directory. 

Cheers )

**Comment by jpwsutton** [comment]
Sure, just download them from:

https://repo.eclipse.org/content/repositories/paho-releases/org/eclipse/paho/org.eclipse.paho.android.service/1.1.1/

and

https://repo.eclipse.org/content/repositories/paho-releases/org/eclipse/paho/org.eclipse.paho.client.mqttv3/1.1.0/

**Comment by Serob** [comment]
Nice, thnaks ;)
