### ISSUE TITLE
message's topic pattern

### ISSUE THREAD

**Issue by aigit** [eclipse/paho.mqtt.android#186]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__

__Android Version Bug Seen on:__

Please also check that if you have found the bug in the Release version (1.1.1) that you check that it also exists in the Snapshot (1.1.2-SNAPSHOT) before raising a bug.

## Description of Bug:
E.g. Steps to re-create, how often does this happen etc..

## Console Log output (if available):

I can't subscribe topic  like 'p/+/p1', so i get a Exception like this 'The topic name MUST NOT contain any wildcard characters (#+)'.
means incompatible with MQTT protocol？

**Comment by jpwsutton** [comment]
You shouldn't get that error if you are subscribing with a wildcard as they are allowed for subscriptions, however they are not allowed for publishing a message. You should have a stack trace which would help us track down why the exception was thrown..

**Comment by aigit** [comment]
Very sorry,I found the reason.that's my mistake in my code. @jpwsutton

**Comment by jpwsutton** [comment]
No worries!
