### ISSUE TITLE
Not receiving messages after a while

### ISSUE THREAD

**Issue by jflavio1** [eclipse/paho.mqtt.android#192]
Hi everyone,

I have implemented a custom MqttService in my app and having trouble on receiving messages from server. The issue is very simple to explain.

Device is connected and subscribed to it's topic. I'm logging every message that comes on "onMessageReceiver()" callback. It can sends requests and receive messages without problems. But **after a time (could be 20 minutes or 5 hours), devices ONLY CAN SEND REQUESTS and no message is receive.**

Why is this happening? 
Device is still connected to server all the time and no "Suscribe to topic error" callback is called.

I' working with:

org.eclipse.paho:org.eclipse.paho.android.service:1.1.1

org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.1-SNAPSHOT

Hope you can help me!!

**Comment by jpwsutton** [comment]
Hi,

It sounds like you are connecting with cleanSession=True. If the connection is lost at any point then all subscriptions would be lost and so when the connection is remade you would not receive any new messages.

There are two ways that you could fix this:

1. You could change the cleanSession flag to false in your connect options. This will mean that as long as you reconnect with the same client id, then your subscriptions will still be honoured.

2. In the reconnection logic, you could resubscribe to your subscriptions.

**Comment by jflavio1** [comment]
@jpwsutton I'm setting cleanSession = false. So that's why is weird. 
Now, server (using NodeJs and Mosca) is having an object TTL with a paramenter like 'subscription_timeout = 10 min'. The broker is unsubscribing devices 10 minutes after subscription is done but the problem here is: **device never knows when server unsubscribes it so it will never try to 'resubscribe'**, there is no callback for unsubscription or something like that...

Thanks for the answer, hope you can help me

**Comment by jpwsutton** [comment]
Ah that would explain it then, no there is no provision in the MQTT specification to tell clients that their subscription has been removed. Sounds like it would be better to remove that subscription_timeout parameter.

**Comment by jflavio1** [comment]
I was thinking it was going to be the only solution. Thanks for the answer 👍
