### ISSUE TITLE
MqttAndroidClient receives multiple simultaneous onFailure callbacks after calling connect more than once

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.android#2]
migrated from Bugzilla [#486520](https://bugs.eclipse.org/bugs/show_bug.cgi?id=486520)
status UNCONFIRMED severity *normal* in component *MQTT-Android* for *1.2*
Reported in version *1.2* on platform *Other*
Assigned to: James Sutton

On 2016-01-25 18:03:42 -0500, Jeffrey Charles wrote:

> I have some code that attempts to connect to MQTT again in 5 seconds if it fails to establish a connection (this is designed for a kiosk with no input devices attached so error handling options are kind of limited other than fully restarting the device). What I'm seeing is that if I pass an invalid MQTT URL, the number of times onFailure is called with the same IMqttToken instance starts increasing very quickly causing the application to crash. What I would expect is onFailure to be called once for a given connection attempt.
> 
> Here's some of the code, you can call connect() after creating the MqttAndroidClient with an invalid MQTT url and using MemoryPersistence to see a repro situation.
> 
>     @DebugLog
>     private void connect() {
>         MqttConnectOptions connectOptions = new MqttConnectOptions();
>         final int TWO_SECONDS = 2000;
>         connectOptions.setConnectionTimeout(TWO_SECONDS);
>         try {
>             mqttAndroidClient.connect(connectOptions, null, connectionCallback);
>         } catch (MqttException e) {
>             Timber.w(e, "Failed to connect to mqtt with MqttException");
>             scheduleConnectAttempt();
>         }
>     }
> 
>     @DebugLog
>     private void scheduleConnectAttempt() {
>         scheduledExecutorService.schedule(connectionRunnable, 5, TimeUnit.SECONDS);
>     }
> 
>     @DebugLog
>     private class MqttConnectRunnable implements Runnable {
>         @Override
>         public void run() {
>             try {
>                 connect();
>             } catch (Throwable t) {
>                 Timber.e(t, "Got exception during connect");
>             }
>         }
>     }
> 
>     @DebugLog
>     private class MqttConnectionCallback implements IMqttActionListener {
>         @Override
>         public void onSuccess(IMqttToken iMqttToken) {
>             eventBus.post(new ConnectedToMqtt());
>         }
> 
>         @Override
>         public void onFailure(IMqttToken iMqttToken, Throwable throwable) {
>             Timber.w(throwable, "Failed to connect to mqtt");
>             scheduleConnectAttempt();
>         }
>     }
> 
> I suspect the source of the problem is the unguarded call to `registerReceiver(MqttAndroidClient.this)` on line 433 in org.eclipse.paho.android.service/org.eclipse.paho.android.service/src/org/eclipse/paho/android/service/MqttAndroidClient.java. Calling registerReceiver with the same object multiple times will result in that object receiving any single broadcast the same number of times it was registered. In my case, calling connect multiple times causes registerReceiver to add the instance as a new receiver each time which causes onReceive to get called that many times for any given single connection attempt resulting in my onFailure method getting called that many times on failure for a given connection attempt. The behaviour I would expect is that registerReceiver would only get called once for a given instance of MqttAndroidClient.

On 2016-01-26 05:23:12 -0500, James Sutton wrote:

> Hi, I believe that this issue has been resolved in the develop branch.
> Could you try this with the SNAPSHOT version of the Android Service & MQTTv3 client?
> 
> Change your repository to: https://repo.eclipse.org/content/repositories/paho-snapshots/
> Change the mqtt client & and Android service version to: 1.0.3-SNAPSHOT

**Comment by andycampbell92** [comment]
Hi,

I also have this problem, it seems that it is not just the onFailure and onSuccess callbacks that get called multiple times it seems that it genuinely sets up multiple connections. Even if I remove the callbacks completely I still receive multiple calls to the messageArrived handler for a single message.

**Comment by andycampbell92** [comment]
I can confirm using the 1.03 snapshot fixed the problem:
`repositories {
    mavenCentral()
    maven { url 'https://repo.eclipse.org/content/repositories/paho-snapshots/' }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'org.eclipse.paho:org.eclipse.paho.android.service:1.0.3-SNAPSHOT'
    compile 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.0.3-SNAPSHOT'
}`

**Comment by jpwsutton** [comment]
Thanks for letting us know! The Snapshot will be made into a full release around May / June time so you'll be able to go back to using a normal release then.
