### ISSUE TITLE
Unable to build the sample application

### ISSUE THREAD

**Issue by shainsingh89** [eclipse/paho.mqtt.android#210]
- [ ] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__

__Android Version Bug Seen on:__

## Description of Bug:
- Pull the master branch
- Android studio 2.3.2

## Console Log output (if available):
Error:(210, 18) error: cannot find symbol class MqttException
Error:(31, 38) error: package org.eclipse.paho.client.mqttv3 does not exist
Error:(78, 43) error: cannot find symbol class MqttCallbackExtended
Error:(29, 38) error: package org.eclipse.paho.client.mqttv3 does not exist
Error:(34, 38) error: package org.eclipse.paho.client.mqttv3 does not exist
Error:(30, 38) error: package org.eclipse.paho.client.mqttv3 does not exist
Error:(28, 38) error: package org.eclipse.paho.client.mqttv3 does not exist
Error:(35, 38) error: package org.eclipse.paho.client.mqttv3 does not exist
Error:(107, 53) error: cannot find symbol class MqttConnectOptions
Error:(203, 13) error: cannot find symbol class MqttMessage
Error:(78, 26) error: cannot access IMqttAsyncClient
class file for org.eclipse.paho.client.mqttv3.IMqttAsyncClient not found
Error:(33, 38) error: package org.eclipse.paho.client.mqttv3 does not exist
Error:(119, 69) error: cannot find symbol class IMqttActionListener
Error:(203, 39) error: cannot find symbol class MqttMessage
Error:(186, 67) error: cannot find symbol class IMqttMessageListener
Error:(173, 73) error: cannot find symbol class IMqttActionListener
Error:(32, 38) error: package org.eclipse.paho.client.mqttv3 does not exist
Error:(138, 18) error: cannot find symbol class MqttException
Error:(107, 9) error: cannot find symbol class MqttConnectOptions
Error:(27, 38) error: package org.eclipse.paho.client.mqttv3 does not exist

:org.eclipse.paho.android.service:compileDebugAndroidTestRenderscript

**Comment by shainsingh89** [comment]
After commenting the **configurations.compile.exclude module: 'org.eclipse.paho.client.mqttv3'**

this new error is coming when try to run the application on device.

Error:Execution failed for task ':paho.mqtt.android.example:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK bundle.properties
	File1: D:\SampleProject\paho.mqtt.android\paho.mqtt.android.example\libs\org.eclipse.paho.client.mqttv3-1.1.0-sources.jar
	File2: C:\Users\Shain\.gradle\caches\modules-2\files-2.1\org.eclipse.paho\org.eclipse.paho.client.mqttv3\1.1.0\89d827ffa47c241f2627421ef1d6c7a8c207a341\org.eclipse.paho.client.mqttv3-1.1.0.jar
	File3: D:\SampleProject\paho.mqtt.android\paho.mqtt.android.example\build\intermediates\exploded-aar\org.eclipse.paho\org.eclipse.paho.android.service\1.1.1\jars\classes.jar

**Comment by leohan1992** [comment]
any solution？I‘m new on that,How can I run sample...

**Comment by shainsingh89** [comment]
@leohan1992  ya its working.

Just change in gradle file in dependency comment the exclude module: "org.eclipse.paho.client.mqttv3"

`compile (project(':org.eclipse.paho.android.service')){
        //exclude module: "org.eclipse.paho.client.mqttv3"
        transitive=true
    }`

**Comment by leohan1992** [comment]
got it

**Comment by Srishesh** [comment]
Cannot run the sample application. getting following error even after commenting the above lines : 

Information:Gradle tasks [:org.eclipse.paho.android.sample:assembleDebug]
/home/srishesh/paho_android/paho.mqtt.android/org.eclipse.paho.android.sample/src/main/java/org/eclipse/paho/android/sample/model/ReceivedMessage.java
Error:(9, 42) error: cannot find symbol class MqttMessage
Error:(16, 19) error: cannot find symbol class MqttMessage
Error:(23, 12) error: cannot find symbol class MqttMessage
/home/srishesh/paho_android/paho.mqtt.android/org.eclipse.paho.android.sample/src/main/java/org/eclipse/paho/android/sample/activity/Connection.java
Error:(16, 38) error: package org.eclipse.paho.client.mqttv3 does not exist
Error:(17, 38) error: package org.eclipse.paho.client.mqttv3 does not exist
Error:(18, 38) error: package org.eclipse.paho.client.mqttv3 does not exist
Error:(69, 13) error: cannot find symbol class MqttConnectOptions
Error:(300, 38) error: cannot find symbol class MqttConnectOptions
Error:(309, 12) error: cannot find symbol class MqttConnectOptions
Error:(369, 70) error: cannot find symbol class MqttException
Error:(390, 64) error: cannot find symbol class MqttException
Error:(416, 46) error: cannot find symbol class MqttMessage
Error:(376, 33) error: cannot access IMqttAsyncClient
class file for org.eclipse.paho.client.mqttv3.IMqttAsyncClient not found
Error:(383, 27) error: cannot find symbol class MqttException
/home/srishesh/paho_android/paho.mqtt.android/org.eclipse.paho.android.sample/src/main/java/org/eclipse/paho/android/sample/activity/ActionListener.java
Error:(12, 38) error: package org.eclipse.paho.client.mqttv3 does not exist
Error:(13, 38) error: package org.eclipse.paho.client.mqttv3 does not exist
Error:(24, 40) error: cannot find symbol class IMqttActionListener
Error:(95, 27) error: cannot find symbol class IMqttToken
Error:(193, 27) error: cannot find symbol class IMqttToken
Error:(94, 5) error: method does not override or implement a method from a supertype
Error:(180, 18) error: cannot find symbol class MqttException
Error:(192, 5) error: method does not override or implement a method from a supertype
/home/srishesh/paho_android/paho.mqtt.android/org.eclipse.paho.android.sample/src/main/java/org/eclipse/paho/android/sample/activity/SubscriptionFragment.java
Error:(79, 26) error: cannot find symbol class MqttException
Error:(128, 26) error: cannot find symbol class MqttException
/home/srishesh/paho_android/paho.mqtt.android/org.eclipse.paho.android.sample/src/main/java/org/eclipse/paho/android/sample/activity/MainActivity.java
Error:(261, 13) error: cannot find symbol class MqttConnectOptions
Error:(187, 48) error: incompatible types: MqttCallbackHandler cannot be converted to MqttCallback
Error:(190, 13) error: cannot find symbol class MqttConnectOptions
Error:(204, 18) error: cannot find symbol class MqttException
Error:(226, 44) error: incompatible types: MqttCallbackHandler cannot be converted to MqttCallback
Error:(232, 9) error: cannot find symbol class MqttConnectOptions
Error:(250, 16) error: cannot find symbol class MqttException
Error:(263, 9) error: cannot find symbol class MqttConnectOptions
Error:(263, 43) error: cannot find symbol class MqttConnectOptions
Error:(292, 44) error: incompatible types: MqttCallbackHandler cannot be converted to MqttCallback
Error:(296, 16) error: cannot find symbol class MqttException
Error:(306, 18) error: cannot find symbol class MqttException
Error:(319, 90) error: incompatible types: ActionListener cannot be converted to IMqttActionListener
Error:(320, 18) error: cannot find symbol class MqttException
/home/srishesh/paho_android/paho.mqtt.android/org.eclipse.paho.android.sample/src/main/java/org/eclipse/paho/android/sample/activity/MqttCallbackHandler.java
Error:(22, 38) error: package org.eclipse.paho.client.mqttv3 does not exist
Error:(23, 38) error: package org.eclipse.paho.client.mqttv3 does not exist
Error:(30, 38) error: cannot find symbol class MqttCallback
Error:(78, 44) error: cannot find symbol class MqttMessage
Error:(97, 32) error: cannot find symbol class IMqttDeliveryToken
Error:(54, 3) error: method does not override or implement a method from a supertype
Error:(77, 3) error: method does not override or implement a method from a supertype
Error:(96, 3) error: method does not override or implement a method from a supertype
/home/srishesh/paho_android/paho.mqtt.android/org.eclipse.paho.android.sample/src/main/java/org/eclipse/paho/android/sample/internal/Persistence.java
Error:(203, 9) error: cannot find symbol class MqttConnectOptions
Error:(204, 9) error: cannot find symbol class MqttMessage
Error:(351, 13) error: cannot find symbol class MqttConnectOptions
Error:(351, 43) error: cannot find symbol class MqttConnectOptions
Error:Execution failed for task ':org.eclipse.paho.android.sample:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by brspurri** [comment]
Same as @Srishesh

**Comment by Raghu94** [comment]
Same as @Srishesh here.

**Comment by jpwsutton** [comment]
Odd.. I've just spun up a completely clean environment with Android Studio 2.3.3, everything worked as expected. Could you check that you have the latest changes from the master branch, the latest version of Gradle installed and that you've cleaned your project.

**Comment by sontono** [comment]
I was suffering same problem, and it has solved after cleaning project, as suggested by @jpwsutton . Th.
