### ISSUE TITLE
code format

### ISSUE THREAD

**Issue by hannesa2** [eclipse/paho.mqtt.android#256]
I see everyone committed in this rep with his own code style. May I suggest a checked in code-formatter ?
I suggest a way, where coworker has nothing to do by add into `.gitignore`

```
!.idea/
.idea/*
!codeStyleSettings.xml
```
and I do a init reformat of complete project.

If you agree, I can make a PR

**Comment by jpwsutton** [comment]
@hannesa2 This sounds like a very useful contribution, things have been slipping over the past few years so it would be good to get everything consistent again. If you'd like to put a PR forwards, that would be great!

**Comment by hannesa2** [comment]
related to https://github.com/eclipse/paho.mqtt.android/pull/257
