### ISSUE TITLE
Gradle tasks run Exception

### ISSUE THREAD

**Issue by Rairmmd** [eclipse/paho.mqtt.android#270]
Error:Execution failed for task ':module_lock:transformClassesWithInstantRunForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.SecurityException: SHA-256 digest error for org/eclipse/paho/client/mqttv3/MqttException.class

**Comment by rajeshkanna777** [comment]
@Rairmmd Hi please disable the InstantRun then it will be work

**Comment by Rairmmd** [comment]
@rajeshkanna777 it's Ok,thanks

**Comment by X287210480X** [comment]
> @Rairmmd嗨，请禁用InstantRun然后它将工作

good
