### ISSUE TITLE
targetSdkVersion 26 and background Service

### ISSUE THREAD

**Issue by hannesa2** [eclipse/paho.mqtt.android#281]
https://github.com/eclipse/paho.mqtt.android/blob/3e7f602188ae5ba0c7ca3815c81f0c39e339543e/org.eclipse.paho.android.service/build.gradle#L11

With api26, background services are changed https://developer.android.com/about/versions/oreo/background.html fundamental for this usage.

Solution 1 with forground services
+ pro: easy to do
- con: a background notification is shown 👎 

Solution 2 with [JobScheduler](https://developer.android.com/reference/android/app/job/JobScheduler.html) 
+ pro : no background notification 👍 
- con : more coding

Does someone has made solution 2 JobScheduler with MQ ? Does it work properly

**Comment by Baxtex** [comment]
Yeah I wonder about solution 2 aswell. Been debugging my app for a while, not understanding why it didn't receive messages sometimes. Turns out, Android kills the service when phone goes idle. Then I found about this JobScheduler but I'm not sure how to use it.

**Comment by Hemant0601** [comment]
Yes, I have used this and is working perfectly fine. 
Have a look at below article to create a JOB Scheduler
http://www.vogella.com/tutorials/AndroidTaskScheduling/article.html

Keep, your background service task only for version below OREO.

Now whenever your JOB starts check if the connection is active or not, if not then invoke MQTT connect();

**Comment by Baxtex** [comment]
@Hemant0601 

So you mean that a possible solution is to Schedule a job as often as you want updates? So let's say I schedulue a job to run each hour, then Android will decide if it will run or not, according to doze. If it is allowed to run, it will try to reconnect to the Mqtt broker if the connection is not active?

**Comment by Hemant0601** [comment]
Your scheduled job will run based on the timer you have feed and once its running then you check if the connection is active or not and if not then connect it again.

What I understand here are two cases 
1. Messages like chat app - In this case if the app is in the background or foreground connection is alive and you will receive messages, but if connection drops you wont receive any messages, in that case you need to be sure to make connection alive and always connected.
QOS attached to a message also plays a role where if you connect to the MQTT it send the previous messages which were not delivered.
2.  If you just need to check things periodically, you can do what you have mentioned.

You can explain your problem in more detail so I can suggest a solution for that too, I have used MQTT to create a Chat application so may be I can relate to the issue you are facing.

**Comment by Baxtex** [comment]
@Hemant0601 
Alright, then option 2 should work for me. 

I have a rather simple scenario but my intention is to scale it up in the future. At the moment I have an arduino measuring the temperature in my house about every 30 minute. When it has measured, it sends it to the broker. The app on the phone should get the message and store it in a local db for later use. So timing isn't critial for me, as long as I get a message at least once an hour I would be happy. I'm not sure about the QOS settings though. Let's say my arduinio sent message at 12:00, 12:30 and 13:00. If my app was in doze at 12:00 and woke up at 12:59, would it only receive the 13:00 message or would it also get 12:00 and 12:30?

**Comment by Hemant0601** [comment]
@Baxtex Ok, what I understood from the MQTT and basic use case is that these things work in below scenario.
1. Where all the data from an IOT device sent to a server and then another client access that information.
2. Where data directly sent to your client(Mobile device) and then you process that information, 

So you are falling in the 2nd case. Now these things work like in continuity, like controlling the device from your phone. In your use case you are gathering information from the device and saving it somewhere(your phone in this case). So understand that MQTT doesnt support offline messages directly, so you wont be getting the messages that are sent from your device to your phone. However you will receive the messages if you have below settings for your messages, i.e QOS [https://mosquitto.org/man/mqtt-7.html](here).
Best possible way to achieve your requirement is 
1. have a light server just with MQTT and keep the connection alive at server to save the data
2. if you dont want to involve server then, in your phone you have to keep running a background service or JOB SERVICE which will save your data from MQTT.

**Comment by Baxtex** [comment]
@Hemant0601 
I see. 
I have been thinking about option 1, but that means, just like you said, I need yet another server, with a database, to store all the values. I don't have the option to run my own unfortunatly but I do have a student subscription at Azure, so I suppose that is a option. Still, I would have liked to keep this thing lightweight and not relying on yet another service/company. If I go for this option I could remove the mqtt client from the app entirely and just have a scheduled job to fetch things from the database instead. 

Regarding QoS, your link didn't work but I found something here: https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels
It seems to me that I should be using QoS 2 to guarantee that I get the message if I go for option 2. 

I'm not sure about the terminology here. There are Services, Jobservices, jobscheduler etc. I will experiment with the jobscheduler and see if I can get the suggestion I gave before to work.

**Comment by Hemant0601** [comment]
@Baxtex Sorry for the link.
Good you found QOS details.
Yes, if you schedule a JOB it will eventually use the battery but not sure about the stats that you are getting for battery drain per hour. Android specifically to reduce battery drain did this. Might be the case you be doing something wrong, but if not then thats the possible case. Let me know if any other help needed.

**Comment by ygModesto** [comment]
Other solution is https://github.com/firebase/firebase-jobdispatcher-android

**Comment by nguyenvanquan7826** [comment]
Hi, have anyone try use JobScheduler to call MqttService? Please help me, now I start forground MqttService and always have once notify of system say "MyApp is running in backgroud".

**Comment by IslamSalah** [comment]
Solution 3 pass the application context as the 1st argument to `MqttAndroidClient` constructor

Pros:
* No need to update the library code (Easy to do)
* No background notification (as in Solution 1)

Cons:
* Not obvious why it solves the issue

behind the scenes the passed component is bound to the service `MqttService` which prevent it from being stopped by the system even if the app is idle and on device with API level 26 or higher

**Comment by hannesa2** [comment]
> "_obvious why it solves the issue_"

@IslamSalah Please can you make a branch and share it with us, to be able to see what you did exactly

**Comment by IslamSalah** [comment]
```
MqttAndroidClient client = new MqttAndroidClient(getApplicationContext(), HOST_URL, CLIENT_ID);
client.connect()
```
If I understand correctly, on calling connect(), the passed context, 1st argument in the constructor, binds as shown [here](https://github.com/eclipse/paho.mqtt.android/blob/master/org.eclipse.paho.android.service/src/main/java/org/eclipse/paho/android/service/MqttAndroidClient.java#L425) to the **created background service** which protects it from being destroyed by the system on API level 26 or above.

**On API Level 26 or higher,** using `getApplicationContext()` and putting the device on idle mode, the service will still be running however if you did the same but with passing a short-lived context, e.g activity instance, in constructor, the system will stop the service a little bit after the activity is destroyed

**On API Level < 26**, whatever the context you passed, the service won't be stopped by the system when the device goes to background.

**Comment by akkitech** [comment]
> @Baxtex Sorry for the link.
> Good you found QOS details.
> Yes, if you schedule a JOB it will eventually use the battery but not sure about the stats that you are getting for battery drain per hour. Android specifically to reduce battery drain did this. Might be the case you be doing something wrong, but if not then thats the possible case. Let me know if any other help needed.

Hi 

> ```
> MqttAndroidClient client = new MqttAndroidClient(getApplicationContext(), HOST_URL, CLIENT_ID);
> client.connect()
> ```
> 
> If I understand correctly, on calling connect(), the passed context, 1st argument in the constructor, binds as shown [here](https://github.com/eclipse/paho.mqtt.android/blob/master/org.eclipse.paho.android.service/src/main/java/org/eclipse/paho/android/service/MqttAndroidClient.java#L425) to the **created background service** which protects it from being destroyed by the system on API level 26 or above.
> 
> **On API Level 26 or higher,** using `getApplicationContext()` and putting the device on idle mode, the service will still be running however if you did the same but with passing a short-lived context, e.g activity instance, in constructor, the system will stop the service a little bit after the activity is destroyed
> 
> **On API Level < 26**, whatever the context you passed, the service won't be stopped by the system when the device goes to background.
> 
> @hannesa2 If it's still unclear, please let me know.

Hi @IslamSalah We tried with the applicationContext() but still the mqtt service is not running when app is being closed by the user. Any clues?

**Comment by IslamSalah** [comment]
@akkitech Thank you for your question. 
My attempts were concerned with the death of the background service when the app is considered idle on API level 26 or more rather than when the user deliberately closes the app.

**Comment by akkitech** [comment]
@IslamSalah we have a use case (chat app) where We want mqtt Service to be running in background even when the user closes the app. We want this for Android 7+
