### ISSUE TITLE
Connection disconnected abnormally,connectionLost(Throwable cause)  method not called

### ISSUE THREAD

**Issue by CoderBigL** [eclipse/paho.mqtt.android#320]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__

__Android Version Bug Seen on:__

this is my gradle:
implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.0'
implementation('org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'

## Description of Bug:
As stated in the title，I found that this phenomenon only occurs when the data is constantly being sent.
I found the source code and found that the reason is that the connection will only send a ping message when there is no data to send or received.
This may not be a bug, but a different design.  But the reality is that the connection has indeed been disconnected.

Can the MqttAndroidClient  provide a method like  MqttAsyncClient.checkPing() ？So we can call this method manually sometimes.

**Comment by angelos3lex** [comment]
@CoderBigL what was your solution here?
