### ISSUE TITLE
Timeout of broadcast BroadcastRecord MqttService.pingSender

### ISSUE THREAD

**Issue by xarionxrc** [eclipse/paho.mqtt.android#335]
Please fill out the form below before submitting, thank you!

- [X] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on: 26

__Android Version Bug Seen on:__

## Description of Bug:
My APK responds to a broadcast message by writing to the SPI bus via native JNI code. After receiving a few broadcast messages and calling the JNI function MQTT produces the error below. If I remove the broadcast receiver for this the error does not occur. I am not sure how calling the JNI functions would influence the operation of the Mqtt ping sender.

If I operate the JNI functions and the MQTT client in separate apps there is no problem.

## Console Log output (if available):
01-09 17:44:29.566 662-683/system_process W/BroadcastQueue: Timeout of broadcast BroadcastRecord{42774100 u0 MqttService.pingSender.352056090145240} - receiver=android.os.BinderProxy@42728638, started 60009ms ago
01-09 17:44:29.671 662-683/system_process I/ANRManager: startAsyncDump: AnrDumpRecord{ Broadcast of Intent { act=MqttService.pingSender.352056090145240 flg=0x14 (has extras) } ProcessRecord{42644940 23160:com.mami.mmdm/u0a34} IsCompleted:false IsCancelled:false }
01-09 17:44:29.674 662-683/system_process I/ActivityManager: appNotResponding-before get this lock: ProcessRecord{42644940 23160:com.mami.mmdm/u0a34} Broadcast of Intent { act=MqttService.pingSender.352056090145240 flg=0x14 (has extras) }

full log and other info:
[mqttlog.txt](https://github.com/eclipse/paho.mqtt.android/files/2742370/mqttlog.txt)

**Comment by xarionxrc** [comment]
Problem has been resolved, there was a memory leak in the JNI functions errors was not created by MQTT

**Comment by DylanStandridge** [comment]
I'm having the exact same issue currently, how exactly did you resolve this?

**Comment by xarionxrc** [comment]
My jni driver was writing 64bytes to memory but in my Java code I was only allocating 16, after some time the incorrect memory was overwritten, perhaps an area  mqtt was using.

**Comment by pradeepartal** [comment]
Hi I am Facing the issue How to solve this ?

 E/ActivityManager: ANR in com.artaldigital.sanad
    PID: 16215
    Reason: Broadcast of Intent { act=MqttService.pingSender.5e844e7240380432c2e43c91 flg=0x80014 (has extras) }
    Load: 0.0 / 0.0 / 0.0
    CPU usage from 0ms to 11437ms later (2020-04-14 19:52:57.032 to 2020-04-14 19:53:08.469):
      38% 1077/surfaceflinger: 21% user + 16% kernel / faults: 677 minor 27 major
      36% 16215/com.artaldigital.sanad: 28% user + 7.5% kernel / faults: 2855 minor 131 major
      12% 1474/media.codec: 7.7% user + 5% kernel / faults: 29884 minor 104 major
      10% 972/android.hardware.graphics.composer@2.3-service: 5% user + 5.7% kernel / faults: 4 minor 5 major
      10% 1975/system_server: 4.7% user + 5.4% kernel / faults: 2824 minor 20 major
      8.5% 5416/com.Slack: 5.8% user + 2.7% kernel / faults: 154 minor 176 major
      4.2% 241/crtc_commit:100: 0% user + 4.2% kernel
      4.1% 4705/kworker/u16:13: 0% user + 4.1% kernel
      4.1% 140/kswapd0: 0% user + 4.1% kernel
      3.3% 1442/media.extractor: 1.3% user + 1.9% kernel / faults: 10233 minor 83 major
      2.8% 3250/com.android.phone: 1.7% user + 1.1% kernel / faults: 1866 minor 665 major
      2.7% 5809/kworker/u16:8: 0% user + 2.7% kernel
      2.3% 5970/com.zhiliaoapp.musically: 1.5% user + 0.7% kernel / faults: 16 minor
      2.2% 3364/kworker/u16:3: 0% user + 2.2% kernel
      2.1% 248/kgsl_worker_thr: 0% user + 2.1% kernel
      2.1% 26133/kworker/u16:10: 0% user + 2.1% kernel
      2% 535/ueventd: 1.5% user + 0.4% kernel
      1.8% 4287/irq/104-1436400: 0% user + 1.8% kernel
      1.7% 1005/vendor.qti.hardware.display.allocator@1.0-service: 0.8% user + 0.8% kernel
      0.1% 1545/media.swcodec: 0% user + 0% kernel / faults: 4365 minor 64 major
      1.3% 4176/sugov:0: 0% user + 1.3% kernel
      1.2% 7/rcu_preempt: 0% user + 1.2% kernel
      1% 17140/kworker/u16:15: 0% user + 1% kernel
      0.9% 2969/com.android.systemui: 0.6% user + 0.3% kernel

**Comment by mishuprovince** [comment]
how to solve it 

2020-09-22 12:00:47.295 523-563/system_process E/ActivityManager: ANR in live.space365.roomboard
    PID: 1738
    Reason: Broadcast of Intent { act=MqttService.pingSender.e7f91ad9-15e8-43cf-a3af-5b72903c1bd6 flg=0x14 (has extras) }
    Load: 0.14 / 0.15 / 0.09
    CPU usage from 317699ms to 0ms ago (2020-09-22 11:55:26.870 to 2020-09-22 12:00:45.815) with 99% awake:
      2.7% 523/system_server: 1.7% user + 1% kernel / faults: 14348 minor 128 major
      0.7% 206/surfaceflinger: 0.3% user + 0.4% kernel / faults: 740 minor
      0.3% 91/kworker/3:1: 0% user + 0.3% kernel
      0.3% 147/mmcqd/2: 0% user + 0.3% kernel
      0.3% 227/media.codec: 0.2% user + 0.1% kernel / faults: 5861 minor 23 major
      0.2% 30/kconsole: 0% user + 0.2% kernel
      0.1% 182/logd: 0% user + 0.1% kernel / faults: 149 minor
      0.1% 216/rild: 0% user + 0.1% kernel / faults: 3 minor
      0% 221/zygote: 0% user + 0% kernel / faults: 4058 minor
      0% 230/mediaserver: 0% user + 0% kernel / faults: 565 minor 6 major
      0% 37/kworker/0:1: 0% user + 0% kernel
      0% 40/cfinteractive: 0% user + 0% kernel
      0% 7/rcu_preempt: 0% user + 0% kernel
      0% 1//init: 0% user + 0% kernel / faults: 211 minor
      0% 6/kworker/u8:0: 0% user + 0% kernel
      0% 222/audioserver: 0% user + 0% kernel / faults: 176 minor
      0% 143/kworker/u8:1: 0% user + 0% kernel
      0% 162/kworker/u8:3: 0% user + 0% kernel
      0% 229/media.extractor: 0% user + 0% kernel / faults: 228 minor 1 major
      0% 225/installd: 0% user + 0% kernel / faults: 28 minor
      0% 231/netd: 0% user + 0% kernel / faults: 1049 minor
      0% 204/lmkd: 0% user + 0% kernel
      0% 157/kworker/u9:1: 0% user + 0% kernel
      0% 205/servicemanager: 0% user + 0% kernel / faults: 1 minor
      0% 223/cameraserver: 0% user + 0% kernel / faults: 311 minor
      0% 181/f2fs_gc-179:14: 0% user + 0% kernel
      0% 190/vold: 0% user + 0% kernel / faults: 49 minor
      0% 200/ueventd: 0% user + 0% kernel
      0% 387/kworker/2:1H: 0% user + 0% kernel
      0% 202/displayd: 0% user + 0% kernel
     +0% 637/kbase_event: 0% user + 0% kernel
     +0% 650/com.android.phone: 0% user + 0% kernel
     +0% 664/com.android.systemui: 0% user + 0% kernel
     +0% 678/com.android.settings: 0% user + 0% kernel
     +0% 703/com.android.inputmethod.latin: 0% user + 0% kernel
     +0% 725/sdcard: 0% user + 0% kernel
     +0% 810/kbase_event: 0% user + 0% kernel
     +0% 1006/android.ext.services: 0% user + 0% kernel
     +0% 1029/com.android.deskclock: 0% user + 0% kernel
     +0% 1049/com.cghs.stresstest: 0% user + 0% kernel
     +0% 1076/com.android.smspush: 0% user + 0% kernel
     +0% 1090/com.android.keychain: 0% user + 0% kernel
     +0% 1121/kbase_event: 0% user + 0% kernel
     +0% 1143/com.android.printspooler: 0% user + 0% kernel
     +0% 1162/com.smartvision.webmeeting: 0% user + 0% kernel
     +0% 1217/kbase_event: 0% user + 0% kernel
     +0% 1231/kworker/u9:2: 0% user + 0% kernel
     +0% 1232/com.android.providers.calendar: 0% user + 0% kernel
     +0% 1252/android.rockchip.update.service: 0% user + 0% kernel
     +0% 1268/android.process.media: 0% user + 0% kernel
     +0% 1290/com.android.quicksearchbox: 0% user + 0% kernel
     +0% 1322/com.android.calendar: 0% user + 0% kernel
     +0% 1351/com.android.email: 0% user + 0% kernel
     +0% 1377/com.android.managedprovisioning: 0% user + 0% kernel
     +0% 1396/com.android.onetimeinitializer: 0% user + 0% kernel
     +0% 1553/adbd: 0% user + 0% kernel
     +0% 1565/logcat: 0% user + 0% kernel
     +0% 1593/kworker/2:2: 0% user + 0% kernel
     +0% 1617/com.android.defcontainer: 0% user + 0% kernel
     +0% 1644/com.android.gallery3d: 0% user + 0% kernel
     +0% 1671/com.android.musicfx: 0% user + 0% kernel
     +0% 1690/android.process.acore: 0% user + 0% kernel
     +0% 1713/com.svox.pico: 0% user + 0% kernel
     +0% 1738/live.space365.roomboard: 0% user + 0% kernel
     +0% 1772/kbase_event: 0% user + 0% kernel
     +0% 1792/kworker/1:2: 0% user + 0% kernel
     +0% 1796/kworker/3:2: 0% user + 0% kernel
    3.5% TOTAL: 1.8% user + 1.2% kernel + 0.3% iowait + 0% softirq
    CPU usage from 935ms to 1447ms later (2020-09-22 12:00:46.749 to 2020-09-22 12:00:47.261):
      5.6% 523/system_server: 1.8% user + 3.7% kernel / faults: 1 minor
        5.6% 563/ActivityManager: 0% user + 5.6% kernel
        1.8% 1198/IpManager.eth0: 1.8% user + 0% kernel
