### ISSUE TITLE
android client 一分钟断线一次

### ISSUE THREAD

**Issue by zwonb** [eclipse/paho.mqtt.android#342]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__mqttv3:1.1.0，service:1.1.1

__Android Version Bug Seen on:__all

Please also check that if you have found the bug in the Release version (1.1.1) that you check that it also exists in the Snapshot (1.1.2-SNAPSHOT) before raising a bug.

![image](https://user-images.githubusercontent.com/22101549/53715618-53474000-3e8d-11e9-90d5-a845c88eafbb.png)
一分钟断线一次，回调这个函数，我进行了重新连接！请问是什么问题导致的？

## Description of Bug:
E.g. Steps to re-create, how often does this happen etc..

**Comment by zwonb** [comment]
![image](https://user-images.githubusercontent.com/22101549/53715843-031cad80-3e8e-11e9-81f1-dc5338f5a3e8.png)

这是掉线后的调试信息

**Comment by zwonb** [comment]
![image](https://user-images.githubusercontent.com/22101549/53715883-234c6c80-3e8e-11e9-9c3c-3ec2c7523538.png)

这是初始化client，client id 不会重复的！

**Comment by byron-xie** [comment]
解决了吗

**Comment by zwonb** [comment]
> 解决了吗

解决了，要给服务器发心跳包

**Comment by contemplator** [comment]
> > 解决了吗
> 
> 解决了，要给服务器发心跳包

請問要怎麼給服務器發心跳包？

我目前遇到的狀況是我的 Android 的 MQTT Client 在和 .Net core 2.2 使用 MqttNet 3.0.6 建立的 WebSocket over mqtt 的 Broker 上，會有每 2 分鐘斷線的情況，使用 WireShark 檢查後，看起來我的 Client 有對 Broker 定期發出 WebSocket 請求並得到回覆，可是內容沒看到 Ping/Pong 等關鍵字，仍在推測是心跳包沒有處理好。

目前已經在 MqttConnectOptions.setKeepAliveInterval(60);
