### ISSUE TITLE
Error in create variant 'android-aidl' after configuration

### ISSUE THREAD

**Issue by Arion12112** [eclipse/paho.mqtt.android#360]
ERROR: Cannot create variant 'android-aidl' after configuration ':org.eclipse.paho.android.service:debugApiElements' has been resolved

anyone know how to fix this?

**Comment by Tynox** [comment]
I fixed it and made a pull request: https://github.com/eclipse/paho.mqtt.android/pull/354

**Comment by Arion12112** [comment]
solved thanks

**Comment by camelliacafe** [comment]
Dear, how to do pull request in detail, please help me.
