### ISSUE TITLE
How to count  online devices number

### ISSUE THREAD

**Issue by lisa294315871** [eclipse/paho.mqtt.android#368]

**Comment by chintan-mishra** [comment]
This is broker specific information. Every broker implements some kind of `$SYS` topic tree. Look at the link below for more info. You will need to consult your MQTT server's docs.

https://github.com/mqtt/mqtt.github.io/wiki/SYS-Topics

**Comment by chintan-mishra** [comment]
Please close this issue

**Comment by lisa294315871** [comment]
Thank you very much
