### ISSUE TITLE
MQTT connection problem in android (Paho)

### ISSUE THREAD

**Issue by karthikcse** [eclipse/paho.mqtt.android#374]
- [ ] Bug exists Release Version 1.0.2 (Java Repository Master Branch)

## Description of Bug:
app crash when ever the MQTT Brocker termination occur

## Console Log output (if available):
E/AndroidRuntime: FATAL EXCEPTION: MQTT Con: paho1056446537855693
    Process: com.mobitech.mconproject, PID: 16966
    java.lang.NullPointerException: cancel() called with a null PendingIntent
        at android.app.AlarmManager.cancel(AlarmManager.java:945)
        at org.eclipse.paho.android.service.AlarmPingSender.stop(AlarmPingSender.java:86)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:327)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:608)
        at java.lang.Thread.run(Thread.java:760)

**Comment by akteruzzaman816** [comment]
Same problem I faced now. Does anyone have any solution??

**Comment by Joesta** [comment]
No solution as of yet. I am also experiencing the same problem. FATAL EXCEPTION: MQTT Con: paho260179451002981

**Comment by A451323699** [comment]
I've also met it. How to solve this problem？

**Comment by Joesta** [comment]
Let me see the paho library you are using

**Comment by A451323699** [comment]
> Let me see the paho library you are using

  implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.0'
  implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
The two above

**Comment by Joesta** [comment]
Alright. I am using the same libraries as yours. My problem with this exception was forgetting to close mqtt connection when no needed.

**Comment by arindamhit** [comment]
Anyone find the solution?

**Comment by karthikcse** [comment]
The issue has been solved by increasing the MQTT connection limit on the server-side.

**Comment by TheMrPhantom** [comment]
Using paho android service version `org.eclipse.paho:org.eclipse.paho.android.service:1.1.1` fixed it for me

**Comment by hunterkage** [comment]
I confirm what @TheMrPhantom said, by upgrading the library, there is no crash and they are handling if a resource failed to call close as @Joesta said 👍
