### ISSUE TITLE
Investigate broken Espresso tests

### ISSUE THREAD

**Issue by hannesa2** [eclipse/paho.mqtt.android#407]
`openssl s_client -connect iot.eclipse.org:8883 -showcerts `

mentioned in https://github.com/eclipse/paho.mqtt.android/blob/master/org.eclipse.paho.android.service/src/androidTest/assets/updatingCertificates.md

doesn't work anymore

> connect: Operation timed out
> connect:errno=60

@jpwsutton 
Do you have any idea ?

**Comment by fpagliughi** [comment]
The MQTT server at iot.eclipse.org was shut down. 
There's a new one at mqtt.eclipse.org.
