### ISSUE TITLE
Failed to compile sample application (Ubuntu 20)

### ISSUE THREAD

**Issue by kollokollo** [eclipse/paho.mqtt.android#447]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Android Service Repository Master Branch)
- [x ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__

__Android Version Bug Seen on:__

Please also check that if you have found the bug in the Release version (1.1.1) that you check that it also exists in the Snapshot (1.1.2-SNAPSHOT) before raising a bug.

## Description of Bug:
/home/xxx/paho.mqtt.android.example>gradle build

## Console Log output (if available):
> Configure project : 
SDK dir: /opt/android-sdk-linux

> Configure project :org.eclipse.paho.android.sample 
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_burd85ga101uijlbn36n0g7qq.run(/home/xxx/paho.mqtt.android/org.eclipse.paho.android.sample/build.gradle:52)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

FAILURE: Build failed with an exception.

**Comment by hannesa2** [comment]
I merged almost all pull request to my fork https://github.com/hannesa2/paho.mqtt.android

I hope the build works there for you. Please give it a try

**Comment by hannesa2** [comment]
At least the `./gradlew check` runs there on CI with Ubuntu 
https://github.com/hannesa2/paho.mqtt.android/blob/6efa9741d361efd3312115af479c9f03bb3d9b12/.github/workflows/Android-CI-Espresso.yml#L46

**Comment by kollokollo** [comment]
Yes, affirmative,  after upgrading the gradle it now successfully build the app.  Thanks !
