### ISSUE TITLE
MQTTService is binded every connect attempt and not unbinded on disconnect/failure, creating multiple ServiceConnections

### ISSUE THREAD

**Issue by derzhavets** [eclipse/paho.mqtt.android#461]
Please fill out the form below before submitting, thank you!

- [ X ] Bug exists Release Version 1.1.1 (Java Repository Master Branch)

__Android API Version Bug Seen on: 28

__Android Version Bug Seen on: Android Wear OS

## Description of Bug:
I'm trying to connect to the MQTT broker which is unavailable. For each connection retry MQTTAndroidClient creates new binding to MQTTService. This was not the issue until I stumbled upon poor wi-fi connection. So if I first connect successfully and subscribe to all the topics, then it disconnects from broker due to poor wi-fi, all the failing attempts to connect create new binding. So when I do connect afterwards, all my callback are fired as much times as I have ServiceConnection instances (see dump below).

## Console Log output (if available):
output from "adb shell dumpsys activity services"
  * ConnectionRecord{d1482d0 u0 CR com.*secret*.application/org.eclipse.paho.android.service.MqttService:@1f43293}
    binding=AppBindRecord{7fbb65e com.*secret*.application/org.eclipse.paho.android.service.MqttService:com.*secret*.application}
  * ConnectionRecord{496961 u0 CR com.*secret*.application/org.eclipse.paho.android.service.MqttService:@24344c8}
    binding=AppBindRecord{7fbb65e com.*secret*.application/org.eclipse.paho.android.service.MqttService:com.*secret*.application}
  * ConnectionRecord{a99c8c5 u0 CR com.*secret*.application/org.eclipse.paho.android.service.MqttService:@2cdb33c}
    binding=AppBindRecord{7fbb65e com.*secret*.application/org.eclipse.paho.android.service.MqttService:com.*secret*.application}
  * ConnectionRecord{e29681 u0 CR com.*secret*.application/.Communication.CommunicationService:@73e7268}
    binding=AppBindRecord{1cf2055 com.*secret*.application/.Communication.CommunicationService:com.*secret*.application}
  * ConnectionRecord{3b56ff8 u0 CR com.*secret*.application/org.eclipse.paho.android.service.MqttService:@b0d7b5b}
    binding=AppBindRecord{7fbb65e com.*secret*.application/org.eclipse.paho.android.service.MqttService:com.*secret*.application}
    binding=AppBindRecord{7c8da6a com.google.android.wearable.ambient/.AmbientService:com.*secret*.application}
    activity=ActivityRecord{cec9d87 u0 com.*secret*.application/.activities.MainActivity t208}
  * ConnectionRecord{65ff14b u0 CR com.*secret*.application/org.eclipse.paho.android.service.MqttService:@c04b21a}
    binding=AppBindRecord{7fbb65e com.*secret*.application/org.eclipse.paho.android.service.MqttService:com.*secret*.application}
  * ConnectionRecord{fd32c41 u0 CR com.*secret*.application/org.eclipse.paho.android.service.MqttService:@d60c728}
    binding=AppBindRecord{7fbb65e com.*secret*.application/org.eclipse.paho.android.service.MqttService:com.*secret*.application}
  * ConnectionRecord{9923336 u0 CR com.*secret*.application/org.eclipse.paho.android.service.MqttService:@e2e6cd1}
    binding=AppBindRecord{7fbb65e com.*secret*.application/org.eclipse.paho.android.service.MqttService:com.*secret*.application}

**Comment by hitesh-dhamshaniya** [comment]
Hey @derzhavets Did you find the solution to the problem?

**Comment by derzhavets** [comment]
Hey @hitesh-dhamshaniya 
Yes, kind of solution, It turns out this library doesn't intend to work this way. Instead of calling "connect' yourself after each disconnection, you need to call "connect" only once, and let the library do the reconnection automatically. Worked good for my case.
