### ISSUE TITLE
mqtt android client -- When mqtt android client failed to connect to mqtt server, onFailure() in IMqttActionListener is not called.

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.android#57]
migrated from Bugzilla [#442845](https://bugs.eclipse.org/bugs/show_bug.cgi?id=442845)
status RESOLVED severity *normal* in component *MQTT-Android* for *1.1*
Reported in version *1.0* on platform *Other*
Assigned to: Zhang Yang

On 2014-08-29 02:41:16 -0400, Zhang Yang wrote:

> When mqtt android client failed to connect to mqtt server (because of network is not reachable), onFailure() in IMqttActionListener is not called.

On 2014-08-29 02:42:03 -0400, Zhang Yang wrote:

> I will fix it on paho develop branch.

On 2014-09-03 03:33:31 -0400, Zhang Yang wrote:

> Have pushed fix on paho develop branch and wait to merge.

**Comment by ashfaaaa** [comment]
i'm still facing this error on 1.1.1..
