### ISSUE TITLE
messageId attribute of MqttMessage always returns zero

### ISSUE THREAD

**Issue by gholadr** [eclipse/paho.mqtt.android#87]
Please fill out the form below before submitting, thank you!

- [Dont know ] Bug exists Release Version 1.0.2 (Java Repository Master Branch)
- [x ] Bug exists in Snapshot Version 1.0.3 (Android Service Repository Master Branch)

__Android API Version Bug Seen on:__ min sdk 17, target sdk 23

## Description of Bug:
E.g. Steps to re-create, how often does this happen etc..

When overriding the messageArrived method from the MqttCallback interface, we've noticed that the messageId attribute of the MqttMessage object passed as a parameter is not set and always returns `0`. Since we use QoS 2, and according to the MQTT specs, it feels like the messageId should be set to an Integer value. We've verified that the broker does  indeed return an integer value. We are not sure but feels like the issue might be when CommsCallback invokes `deliverMessage`

**Comment by gholadr** [comment]
I found what the issue is. Your ReceivedMqttMessage extends MqttMessage but the messageId setter method in ReceivedMqttMessage is wrong, it should be:

```
public void setMessageId(int msgId) {
		super.setId(msgId);
	}
```

**Comment by jpwsutton** [comment]
@gholadr Where are you seeing `ReceivedMqttMessage`? That's not a class in paho that I recognise...

**Comment by gholadr** [comment]
@jpwsutton, sorry, its this class `org.eclipse.paho.client.mqttv3.internal.wire.MqttReceivedMessage`

**Comment by gholadr** [comment]
Let me submit a PR for this? We need this to be part of 1.2.0 as we rely on message Id to sort messages.

**Comment by jpwsutton** [comment]
We're past the deadline for PRs for 1.2.0 as the IP log has already been submitted, I can look at getting it added myself though.

**Comment by gholadr** [comment]
That would be  awesome if you could.

**Comment by jpwsutton** [comment]
Fix is now in the latest 1.0.3-SNAPSHOT and will be in 1.1.0 once released.

**Comment by gholadr** [comment]
Thank you.

**Comment by Amptek-Inc** [comment]
Hi,

I am using version 1.1.1, and the id is still always returning 0. Has this issue been fixed?
