### ISSUE TITLE
offline buffering question?

### ISSUE THREAD

**Issue by yon86** [eclipse/paho.mqtt.android#92]
it shows on the paho project page that the library supports this functionality already but it says it doesn't here? Can anyone tell me how this going to work are the messages going to be store in memory or in some sqllite db and send them when connected again etc? thank you for the response

**Comment by jpwsutton** [comment]
The current SNAPSHOT 1.0.3 supports offline buffering, the next released version 1.1.0 will also support this, but there are some tasks that have yet to be completed before we can fully build and publish the JAR and AAR files to Maven Central.

The latest 1.0.3 SNAPSHOT JAR that's available on repo.eclipse.org should do what you need for now though.

Messages are stored in memory, but can also be persisted using whatever persistence mechanism you add in yourself, (currently in-memory and file persistence are bundled)

**Comment by yon86** [comment]
thank you
