### ISSUE TITLE
Gradle sync not working

### ISSUE THREAD

**Issue by yon86** [eclipse/paho.mqtt.android#93]
I started adding the project to a new project on android studio using the steps on the readme but it says 

```Error:(28, 13) Failed to resolve: org.eclipse.paho:org.eclipse.paho.android.service:1.0.2```

I am adding the project in my gradle file as the following
``` compile 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.0.2' ```

  ```  compile 'org.eclipse.paho:org.eclipse.paho.android.service:1.0.2' ```

thanks for the help.

**Comment by jpwsutton** [comment]
@yon86 This may have been because of the migration from repo.eclipse.org to maven central.

Could you try changing all the version numbers from `1.0.2` to `1.1.0` as that is the new stable release.

**Comment by yon86** [comment]
ok thanks
