### ISSUE TITLE
Version 1.1.0

### ISSUE THREAD

**Issue by elsennov** [eclipse/paho.mqtt.android#94]
Hi, what is the gradle script for version 1.1.0? Is it has been released? Thanks

**Comment by ironista** [comment]
Hi, in these days I made my the same question. This is my gradle configuration:

`repositories {
    maven {
        url "https://repo.eclipse.org/content/repositories/paho-releases/"
    }
}

dependencies {
    compile 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.0'
    compile 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.0@aar'
}`

**Comment by elsennov** [comment]
Snapshot works as well. Thanks
