### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by elsennov** [eclipse/paho.mqtt.android#98]
What exactly are the permissions needed for implementing this library? I saw the permissions from sample app, it includes

```
<!-- Permissions the Application Requires -->
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.INTERNET" />
```

Are those permissions, all of it, really needed? Thanks

**Comment by elsennov** [comment]
@jpwsutton Could you please help? Thanks

**Comment by nisrulz** [comment]
A lot the permissions defined are required for provided reason.

@jpwsutton would be better off explaining them (or maybe correcting me if I mention something thats wrong). But here is a small run down of it

+ `<uses-permission android:name="android.permission.WAKE_LOCK" />` - Needed to keep the connection active with broker.i.e not letting the device sleep and get disconnected from the connection to broker.
+ `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />` - Persist messages when selected as a config for the client,
+ `<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />` - Know when the network changes i.e goes offline or comes online 
+ `<uses-permission android:name="android.permission.READ_PHONE_STATE" />` - Not sure about this , but generally  required to know information regarding the device like IMEI id.
+ `<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />` - Read persisted messages
+ `<uses-permission android:name="android.permission.INTERNET" />` - The obvious one , for having connection with the broker over internet.

**Comment by jpwsutton** [comment]
Thanks @nisrulz, that sums it up very well

```READ_PHONE_STATE``` is one that I'm not 100% sure about either. I believe it's necessary for judging the state of the network in some edge cases, but It's quite an invasive permission. Ideally we would be able to get rid of it so I'll have a play later to see how the service works if that permission is not included.

**Comment by elsennov** [comment]
@nisrulz Thank you for the answers! I need the information since there is sensitive permissions, like write and read to ext storage.

**Comment by nisrulz** [comment]
@elsennov @jpwsutton We should also be able to do away with the read and write to external media permissions if we switched to internal storage read and write.

And yeah , I agree with little bit of testing and review we can do away with the `READ_PHONE_STATE` permission, hopefully.

**Comment by Simon-L** [comment]
I am sorry but this isn't documented anywhere and probably should be?
Maybe in the README along with the gradle dependencies to add?

**Comment by ArjunTharani** [comment]
![screenshot 6](https://user-images.githubusercontent.com/47387809/52628137-fd5e2880-2edc-11e9-9577-05997b8574f7.png)
 Tell me How should i resolve it
